config/routes.rb
Dermbids::Application.routes.draw do
  root to: "home#index"

  devise_for :users
  resources :quote_requests, only: [:new, :create]
  namespace :admin do
    get '/', to: 'quote_requests#index', as: 'root'
    resources :quote_requests, only: [:index, :show, :update]
    resources :clinic_communications, only: [:index, :create]
    resources :clinics
  end

  

end

app/models/quote_request.rb
class QuoteRequest < ActiveRecord::Base
  STATUS={
      new: 100,
      active: 200,
      archived: 300,
      revisit: 400
  }

  belongs_to :user
  has_many :clinic_communications

  validates :email, presence: true
  validates :status, inclusion: {in: STATUS.values}, allow_nil: false

  ###### BEGIN Paperclip related settings #####
  has_attached_file :photo,
    storage: :s3,
    s3_credentials: {
        access_key_id: ENV['AMAZON_ACCESS_KEY_ID'],
        secret_access_key: ENV['AMAZON_SECRET_ACCESS_KEY'],
        bucket: ENV['AMAZON_BUCKET'] #TODO change this to an environment variable
    },
    styles: { size320: '320' },
    path: '/:style/:hash.:extension',
    hash_secret: ENV['DERMBIDS_PHOTO_HASH_SECRET'],
    hash_data: ':class/:attachment/:id/:style/'

  validates :photo, attachment_presence: true
  validates :photo, attachment_size: { less_than: 15.megabytes }
  validates :photo, attachment_content_type: { content_type: ['image/png', 'image/gif', 'image/jpg', 'image/jpeg'] }
  ###### Paperclip related settings END #####

  after_initialize do |r|
    if new_record?
      r.status = STATUS[:new]
    end
  end

  def self.filter(filter_hash={})
    result = all.order('id desc')
    result.where(status: QuoteRequest::STATUS[filter_hash[:status].to_sym]).order('id desc') if filter_hash.include? :status
  end

  # Override the status setter so that we can pass it either a string or value
  def status=(value)
    if value.is_a? Symbol
      write_attribute(:status, QuoteRequest::STATUS[value])
    elsif value.is_a? String
      write_attribute(:status, QuoteRequest::STATUS[value.to_sym])
    else
      write_attribute(:status, value)
    end
  end

  def status
    read_attribute(:status)
  end

  def find_or_create_user
    self.user = User.find_or_create_by(email: self.email) if user.nil? && self.email.present?
  end

  def masked_full_name
    full_name[/(\w*\s.|\w*)/] + '**********'
  end

  def first_name
    full_name[/(\w*)/]
  end

  # Creates a ClinicCommunication object to log the fact that a quote request was sent to the given clinic
  def request_quote_from_clinic(clinic, initiated_by_user=nil)
    clinic_communication=self.clinic_communications.create(
        initiated_by_user: initiated_by_user,  # this will normally be current_user
        communication_type: ClinicCommunication::COMMUNICATION_TYPES[:quote_request],
        clinic: clinic,
        quote_request: self
    )
    if clinic_communication.send_email_to_clinic then # TODO this may have to be refactored to become thread safe
      self.update(status: STATUS[:active])
    end
    return clinic_communication
  end

  #TODO Consider refactoring to combine with request_quote_from_clinic - a new method called #send_clinic_communication(*args)?
  def send_patient_details_to_clinic(clinic, initiated_by_user=nil)
    clinic_communication=self.clinic_communications.create(
        initiated_by_user: initiated_by_user,  # this will normally be current_user
        communication_type: ClinicCommunication::COMMUNICATION_TYPES[:send_patient_details],
        clinic: clinic,
        quote_request: self
    )
    clinic_communication.send_email_to_clinic # TODO this may have to be refactored to become thread safe
    return clinic_communication
  end

end

app/controllers/admin/quote_requests_controller.rb
class Admin::QuoteRequestsController < AdminController
  before_action :authenticate_admin_user!
  before_action :set_quote_request, only: [:show, :update]

  # GET /admin/quote_requests
  def index
    @filter = filter_params  # so that we can highlight the currently selected view
    @quote_requests = QuoteRequest.filter(@filter)
  end

  # GET /admin/quote_requests/:id
  def show
    @clinics = Clinic.all # This will later be changed to encompass only clinics in the local area for this quote request
  end

  # PUT, PATCH /admin/quote_request/:id
  def update
    if @quote_request.update(quote_request_params)
      redirect_to admin_quote_request_path(@quote_request), notice: 'Status has been successfully updated.'
    else
      redirect_to admin_quote_request_path(@quote_request), notice: 'An error occurred updating the status of this quote request.'
    end
  end

private
  def filter_params
    if params.include? :filter
      params[:filter]
    else
      { status: :new }  # show only the new quote requests by default
    end
  end

  def set_quote_request
    @quote_request = QuoteRequest.find(params[:id])
  end

  def quote_request_params
    params.require(:quote_request).permit(:status)
  end

end

app/controllers/quote_requests_controller.rb
class QuoteRequestsController < ApplicationController
  # GET /quote_requests/new
  def new
    @quote_request = QuoteRequest.new
  end

  # GET /quote_requests
  def create
    @quote_request = QuoteRequest.new(quote_request_params)

    if @quote_request.save
      render :create
    else
      render :new
    end
  end

private
  def quote_request_params
    params.require(:quote_request).permit(:email, :full_name, :postal_code, :photo, :country)
  end
end

app/views/admin/quote_requests/_clinics_already_quoted.html.haml
#clinics-already-quoted
  -unless @clinics.already_quote_requested(@quote_request).empty? then
    %h3 These clinics you have already requested a quote from:
    %table.table
      -@clinics.already_quote_requested(@quote_request).each do |clinic|
        %tr
          %td{width:"33%"}= clinic.business_name
          %td{width:"33%"}= "#{clinic.city}, #{clinic.state}"
          %td{width:"33%"}
            = form_tag admin_clinic_communications_path, style: "display:inline" do
              =hidden_field_tag 'quote_request_id', @quote_request.id
              =hidden_field_tag 'clinic_id', clinic.id
              =hidden_field_tag 'type', ClinicCommunication::COMMUNICATION_TYPES[:quote_request]
              =submit_tag 'Resend Quote Request', class: "btn btn-default"
            = form_tag admin_clinic_communications_path, style: "display:inline"  do
              =hidden_field_tag 'quote_request_id', @quote_request.id
              =hidden_field_tag 'clinic_id', clinic.id
              =hidden_field_tag 'type', ClinicCommunication::COMMUNICATION_TYPES[:send_patient_details]
              -if clinic.sent_quote_request_patient_details?(@quote_request)
                =submit_tag 'Resend Full Details', class: "btn btn-default"
              -else
                =submit_tag 'Send Full Details', class: "btn btn-info"

app/views/admin/quote_requests/_clinics_not_yet_quoted.html.haml
#clinics-not-yet-quoted
  -if @clinics
    %h3 Select which clinics you would like to forward a quote request:
    %table.table
      -@clinics.not_yet_quote_requested(@quote_request).each do |clinic|
        %tr
          %td= clinic.business_name
          %td= "#{clinic.city}, #{clinic.state}"
          %td
            =form_tag admin_clinic_communications_path do
              =hidden_field_tag 'quote_request_id', @quote_request.id
              =hidden_field_tag 'clinic_id', clinic.id
              =hidden_field_tag 'type', ClinicCommunication::COMMUNICATION_TYPES[:quote_request]
              =submit_tag 'Request Quote', class: "btn btn-info"

app/views/admin/quote_requests/index.html.haml
%ul.nav.nav-tabs
  %li= link_to("New", admin_quote_requests_path(filter: {status: :new}))
  %li= link_to("Active", admin_quote_requests_path(filter: {status: :active}))
  %li= link_to("Archived", admin_quote_requests_path(filter: {status: :archived}))
  %li= link_to("Revisit Later", admin_quote_requests_path(filter: {status: :revisit}))

- if @quote_requests.present? then
  - @quote_requests.each do |q|
    .row.quote-request-summary
      .col-sm-2.image
        =link_to(image_tag(q.photo.url(:size320)), admin_quote_request_path(id:q.id))
      .col-sm-10.detail
        %p=q.created_at
        %p=raw("#{q.full_name} (#{mail_to(q.email)})")
        %p="Postal Code: #{q.postal_code} (#{city_from_zip_code(q.postal_code)})"
- else
  %p No quote requests to display

app/views/admin/quote_requests/show.html.haml
%div.spacer{style:"height: 15px;"}
.row
  .col-sm-4
    -if @quote_request.photo
      =link_to(image_tag(@quote_request.photo.url(:size320), style: "width:100%;"), @quote_request.photo.url)
    -else
      .missing-photo No photo available
  .col-sm-8
    %p= raw("#{@quote_request.full_name} (#{mail_to(@quote_request.email, @quote_request.email)})")
    %p= "Postal Code: #{@quote_request.postal_code} (#{city_from_zip_code(@quote_request.postal_code)})"
    %p= "Country: #{@quote_request.country}"
    %p{style: "display: inline"}
      Status:
      .btn-group
        -current_status_button
        =form_for @quote_request, url: admin_quote_request_path(@quote_request), html: {id: 'change-status-form'} do |f|
          =f.hidden_field :status
        %ul.dropdown-menu{role: "menu"}
          -QuoteRequest::STATUS.keys.each do |k|
            %li= link_to(k.capitalize, "#", :"data-value"=>k, :class=>"change-status-link")
    %hr
    %h3 Email Templates for Patient
    %ul
      %li
        = mail_to @quote_request.email, "Initial Contact with User", subject: "Introduction to Dermbids", body: tattoo_removal_introduction_email_body_for_patient
      %li
        = mail_to @quote_request.email, "Tattoo Removal Estimates from Dermbids", subject: "Dermbids Quote Request Details", body: tattoo_removal_estimates_email_body_for_patient
      %li
        = mail_to @quote_request.email, "Follow up on Tattoo Removal Estimates from Dermbids", subject: "Followup on Dermbids Quote Request", body: tattoo_removal_estimates_followup_email_body_for_patient

:coffee
  $('.change-status-link').click ->
    $('#change-status-form input#quote_request_status').val($(this).attr('data-value'))
    $('#change-status-form').submit()



#select-clinics-for-quote
  = render partial: 'admin/quote_requests/clinics_already_quoted'
  = render partial: 'admin/quote_requests/clinics_not_yet_quoted'