config/routes.rb
Dermbids::Application.routes.draw do
  root to: "home#index"

  devise_for :users
  resources :quote_requests, only: [:new, :create]
  namespace :admin do
    get '/', to: 'quote_requests#index', as: 'root'
    resources :quote_requests, only: [:index, :show, :update]
    resources :clinic_communications, only: [:index, :create]
    resources :clinics
  end

  

end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  belongs_to :quote_request_contact, class_name: :User, foreign_key: :quote_request_contact_user_id
  has_many :clinic_communications
  accepts_nested_attributes_for :quote_request_contact
  attr_accessor :state

  #TODO-TEST Write tests for these scopes
  scope :already_quote_requested, ->(quote_request) { joins(:clinic_communications).where(clinic_communications: { quote_request_id: quote_request, communication_type: ClinicCommunication::COMMUNICATION_TYPES[:quote_request] }).distinct }
  scope :not_yet_quote_requested, ->(quote_request) { where.not(id: ClinicCommunication.eager_load(:clinic).where(clinic_communications: {quote_request_id:quote_request, communication_type: ClinicCommunication::COMMUNICATION_TYPES[:quote_request]}).map { |r| r.clinic_id })  }

  def state
    State.find(self.state_id).abbr if state_id.present?
  end

  def state=(abbr)
    self.state_id = State.find_by(abbr: abbr).id
  end

  def sent_quote_request_patient_details?(quote_request)
    clinic_communications.exists?(quote_request: quote_request, communication_type: ClinicCommunication::COMMUNICATION_TYPES[:send_patient_details]).present?
  end

end

app/controllers/admin/clinics_controller.rb
class Admin::ClinicsController < AdminController
  before_action :set_clinic, only: [:show, :edit, :update]
  before_action :authenticate_admin_user!

  # GET /clinics
  # GET /clinics.json
  def index
    @clinics = Clinic.all
  end

  # GET /clinics/1
  # GET /clinics/1.json
  def show
  end

  # GET /clinics/new
  def new
    @clinic = Clinic.new
    @clinic.build_quote_request_contact(user_type: User::TYPES[:provider])
  end

  # GET /clinics/1/edit
  def edit
  end

  # POST /clinics
  # POST /clinics.json
  def create
    @clinic = Clinic.new(clinic_params)

    respond_to do |format|
      if @clinic.save
        format.html { redirect_to [:admin,@clinic], notice: 'Clinic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @clinic }
      else
        format.html { render action: 'new' }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clinics/1
  # PATCH/PUT /clinics/1.json
  def update
    respond_to do |format|
      if @clinic.update(clinic_params)
        format.html { redirect_to [:admin,@clinic], notice: 'Clinic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1
  # DELETE /clinics/1.json
  def destroy
    @clinic.destroy
    respond_to do |format|
      format.html { redirect_to clinics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clinic
      @clinic = Clinic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clinic_params
      params.require(:clinic).permit(:business_name, :address1, :address2, :city, :state, :postal_code,
        :quote_request_contact_attributes=>[:first_name, :last_name, :email, :id])
    end
end

app/views/admin/clinics/_form.html.erb
<%= form_for([:admin,@clinic]) do |f| %>
  <% if @clinic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clinic.errors.count, "error") %> prohibited this clinic from being saved:</h2>

      <ul>
      <% @clinic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :business_name %><br>
    <%= f.text_field :business_name %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.collection_select :state, State.all, :abbr, :state_name, selected: @clinic.state %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>

  <h2>Contact Information</h2>
  <%= f.fields_for :quote_request_contact do |contact| %>
     <div class="field">

        <%= contact.label "Contact First Name" %><br>
        <%= contact.text_field :first_name %>
     </div>

        <div class="field">
          <%= contact.label "Contact Last Name" %><br>
          <%= contact.text_field :last_name %>
        </div>

        <div class="field">
          <%= contact.label "Contact Email" %><br>
          <%= contact.text_field :email %>
        </div>
  <%end%>

  <br/>
    <br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/clinics/edit.html.erb
<h1>Editing clinic</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @clinic] %> |
<%= link_to 'Back', admin_clinics_path %>

app/views/admin/clinics/index.html.erb
<h1>Listing clinics</h1>

<table>
  <thead>
    <tr>
      <th>Business name</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Postal code</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @clinics.each do |clinic| %>
      <tr>
        <td><%= clinic.business_name %></td>
        <td><%= clinic.address1 %></td>
        <td><%= clinic.address2 %></td>
        <td><%= clinic.city %></td>
        <td><%= clinic.state %></td>
        <td><%= clinic.postal_code %></td>
        <td><%= link_to 'Show', admin_clinic_path(clinic) %></td>
        <td><%= link_to 'Edit', edit_admin_clinic_path(clinic) %></td>
        <td><%= link_to 'Destroy', admin_clinic_path(clinic), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clinic', new_admin_clinic_path %>

app/views/admin/clinics/new.html.erb
<h1>New clinic</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_clinics_path %>

app/views/admin/clinics/show.html.erb
<p>
  <strong>Business name:</strong>
  <%= @clinic.business_name %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @clinic.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @clinic.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @clinic.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @clinic.state %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @clinic.postal_code %>
</p>

<h2>Contact Information</h2>
    <p>

      <strong>Contact First Name</strong><br>
      <%= @clinic.quote_request_contact.first_name %>
    </p>

<p>
      <strong>Contact Last Name</strong><br>
      <%= @clinic.quote_request_contact.last_name %>
</p>

<p>
      <strong>Contact Email</strong><br>
      <%= mail_to @clinic.quote_request_contact.email, @clinic.quote_request_contact.email %>
</p>

<%= link_to 'Edit', edit_admin_clinic_path(@clinic) %> |
<%= link_to 'Back', admin_clinics_path %>