config/routes.rb
Dermbids::Application.routes.draw do
  root to: "home#index"

  devise_for :users
  resources :quote_requests, only: [:new, :create]
  namespace :admin do
    get '/', to: 'quote_requests#index', as: 'root'
    resources :quote_requests, only: [:index, :show, :update]
    resources :clinic_communications, only: [:index, :create]
    resources :clinics
  end

  

end

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    %meta{ :charset => "utf-8" }
    %meta{ 'http-equiv' => "X-UA-Compatible", :content => "IE=Edge,chrome=1" }
    %meta{ :name => "viewport", :content => "width=device-width", 'initial-scale' => "1.0" }
    %title= content_for?(:title) ? yield(:title) : 'Dermbids: Tattoo Removal and More | Costs by Taking a Picture'
    = csrf_meta_tags

    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

  %body
    #wrap
      %nav.navbar.navbar-default.navbar-fixed-top.navbar-admin{role: 'navigation'}
        .navbar-header
          =link_to 'Dermbids Administration', admin_root_path, class: 'navbar-brand'
        -if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li= link_to 'Clinics Admin', admin_clinics_path
            %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
      .container
        -flash.each do |name, msg|
          .alert.alert-warning.alert-dismissable
            =msg
            %button.close{ :type=>'button', :'data-dismiss'=>'alert', :'aria-hidden'=>true }!&times;
        = yield
    #footer
      .container
        %p.text-muted.credit © Copyright 2013 Dermbids Inc. All rights reserved.

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{ :charset => "utf-8" }
    %meta{ 'http-equiv' => "X-UA-Compatible", :content => "IE=Edge,chrome=1" }
    %meta{ :name => "viewport", :content => "width=device-width", 'initial-scale' => "1.0" }
    %title= content_for?(:title) ? yield(:title) : 'Dermbids: Tattoo Removal and More | Costs by Taking a Picture'
    = csrf_meta_tags

    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

  %body
    #wrap
      .navbar.navbar-default.navbar-fixed-top{:role => :navigation}
        .container
          .navbar-header
            -#%button.navbar-toggle{'type' => 'button', 'data-toggle' => 'collapse', 'data-target' => '.navbar-collapse'}
            -#  /%span.sr-only= t("#{i18n_path}.toggle-nav")
            -#  %span.icon-bar
            -#  %span.icon-bar
            -#  %span.icon-bar
            = link_to "Dermbids", root_path, { :class => 'navbar-brand' }
          -#.collapse.navbar-collapse
          -#  %ul.nav.navbar-nav
          -#    - if user_signed_in?
          -#      %li= nav_link t('businesses.search_link'), businesses_path
            %ul.nav.navbar-nav.navbar-right
              = navigation_links
      .container
        = yield
    #footer
      .container
        %p.text-muted.credit © Copyright 2013 Dermbids Inc. All rights reserved.

app/views/layouts/quote_requests.html.haml
!!! 5
%html
  %head
    %meta{ :charset => "utf-8" }
    %meta{ 'http-equiv' => "X-UA-Compatible", :content => "IE=Edge,chrome=1" }
    %meta{ :name => "viewport", :content => "width=device-width", 'initial-scale' => "1.0" }
    %title= content_for?(:title) ? yield(:title) : 'Dermbids: Tattoo Removal and More | Costs by Taking a Picture'
    = csrf_meta_tags

    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

  %body{ style: "background-color: #f5f5f5" }
    #wrap
      .container
        .container-box
          = yield
    #footer
      .container
        %p.text-muted.credit © Copyright 2013 Dermbids Inc. All rights reserved.